using Terminal.Gui;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Calc
{
    public partial class MyView : Terminal.Gui.Window
    {

        List<Terminal.Gui.Attribute> colors = new List<Terminal.Gui.Attribute>()
        {
            //color window
            Application.Driver.MakeColor(Color.Green, Color.Black),

            //color button
            Application.Driver.MakeColor(Color.Black, Color.Green)
        };

        private Terminal.Gui.Label label1;
        private Terminal.Gui.Label label2;
        private Terminal.Gui.Label label3;
        private Terminal.Gui.Label label4;

        private Terminal.Gui.Button button1;

        private Terminal.Gui.TextField textField1;
        private Terminal.Gui.TextField textField2;

        
        private void InitializeComponent()
        {
            this.button1 = new Terminal.Gui.Button();
            this.label1 = new Terminal.Gui.Label();
            this.label2 = new Terminal.Gui.Label();
            this.label3 = new Terminal.Gui.Label();
            this.label4 = new Terminal.Gui.Label();
            this.textField1 = new Terminal.Gui.TextField();
            this.textField2 = new Terminal.Gui.TextField();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.ColorScheme.Normal = colors[0];
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = true;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Press Ctrl+Q to quit";

            this.label1.Width = 5;
            this.label1.Height = 2;
            this.label1.X = Pos.Center();
            this.label1.Y = Pos.Center();
            this.label1.Text = "Калькулятор A+B";
            this.label1.TextAlignment = TextAlignment.Left;
            this.Add(this.label1);


            this.label2.Width = 5;
            this.label2.Height = 2;
            this.label2.X = Pos.Center()-32;
            this.label2.Y = Pos.Center()+1;
            this.label2.Text = "A:";
            this.label2.TextAlignment = TextAlignment.Left;
            this.Add(this.label2);
            this.textField1.AutoSize = true;
            this.textField1.Width = 25;
            this.textField1.X = Pos.Center()-30;
            this.textField1.Y = Pos.Center()+1;
            this.textField1.Height = 2;
            this.textField1.ColorScheme = new ColorScheme() 
            { 
                Normal = colors[0],
                Focus = colors[1],
            };     
            this.textField1.Border = new Border()
            {
                Background = Color.Green,
                BorderStyle = BorderStyle.Single,
                Effect3D = true,
                BorderThickness = new Thickness(5),
                DrawMarginFrame = true,
                
            };

            this.textField1.Data = "txfA";


            this.Add(this.textField1);


            this.label3.Width = 5;
            this.label3.Height = 2;
            this.label3.X = Pos.Center()+5;
            this.label3.Y = Pos.Center() + 1;
            this.label3.Text = "B:";
            this.label3.TextAlignment = TextAlignment.Left;
            this.Add(this.label3);

            this.textField2.AutoSize = true;
            this.textField2.Width = 25;
            this.textField2.X = Pos.Center() +7;
            this.textField2.Y = Pos.Center() + 1;
            this.textField2.Height = 2;
            this.textField2.ColorScheme = new ColorScheme()
            {
                Normal = colors[0],
                Focus = colors[1],
            };
            this.textField2.Border = new Border()
            {
                Background = Color.Green,
                BorderStyle = BorderStyle.Single,
                Effect3D = true,
                BorderThickness = new Thickness(5),
                DrawMarginFrame = true,

            };

            this.textField2.Data = "txfB";


            this.Add(this.textField2);

            this.button1.Width = 12;
            this.button1.X = Pos.Center();
            this.button1.Y = Pos.Center() + 3;
            this.button1.Data = "button1";
            this.button1.Text = "cчитать";
            this.button1.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button1.IsDefault = false;
            this.button1.ColorScheme = new ColorScheme
            {
                Focus = colors[1],
                Normal = colors[0],
            };
            this.Add(this.button1);


            this.label4.Width = 20;
            this.label4.Height = 7;
            this.label4.X = Pos.Center();
            this.label4.Y = Pos.Center() + 7;
            this.label4.TextAlignment = TextAlignment.Centered;
            this.Add(this.label4);
        }
    }
}
