using Terminal.Gui;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Calc
{
    public partial class MyView
    {

        public MyView()
        {
            InitializeComponent();
            button1.Clicked += () => {
                try
                {

                if (textField1.Text != null && textField2.Text != null)
                {
                        int x = int.Parse(textField1.Text.ToString()) + int.Parse(textField2.Text.ToString());


                        label4.Text = x.ToString();
                }
            
                }
                catch {

                    label4.Text = "¬ведены некоректные данные";

                }
            };
        }
    }
}
